name: Parent Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-child-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Child Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.kind }}  # Personal Access Token with repo scope
          repository: matze240/kind
          event-type: start-child-workflow
